### ISSUE TITLE
Startup errors

### ISSUE THREAD

**Issue by aahenn** [mhumphries2323/Transcription_Pearl#1]
I've run into a few minor issues while trying to run the program on Linux Mint 21.3

When initially running the script, there's a ModuleNotFoundError related to ImageSplitter, the sub-utility that's not included in this release. Just commenting out line 12 seemed to do the trick though.

Separately, I also get the following error:
line 37, in __init__
    self.iconbitmap('util/pb.ico')
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2109, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "util/pb.ico" not defined

Some initial googling suggests tkinter on Linux may not play nicely with .ico files. Again, commenting out the line worked, though at the tragic expense of missing out on the icon.

Very excited to dig in further!

**Comment by mhumphries2323** [comment]
Thank you for this, I've updated the release with a note. I also fixed a small bug with the correct text function which was preventing the program from extracting the right text resulting in text that read "Error". In cutting out a number of features that I was testing, I had some code fragments still hanging around. Appreciate the help!
