### ISSUE TITLE
Image orientation

### ISSUE THREAD

**Issue by aahenn** [mhumphries2323/Transcription_Pearl#3]
**The issue**
Some imported images lose their proper orientation. The AI models are surprisingly good at OCRing images that are the wrong way round, but there's at least some loss in accuracy.
![Screenshot from 2024-11-09 09-35-42](https://github.com/user-attachments/assets/6b0995a5-5dde-42f0-bf5b-368cc39cb1cc)

**The cause**
My understanding is that many cell phone cameras, instead of rotating their photos based on whether the device is being held upright or horizontally, just indicate each image's orientation using EXIF metadata. Most applications check that metadata and display the image accordingly, so users are none the wiser. But by default Pillow simply loads the image as-is.

**Potential solution**
I think if you import the Pillow ImageOps module and add something like this to the resize_image function, that might do it.

```
# Rotate image to match EXIF orientation
img = ImageOps.exif_transpose(img)
```

**Comment by mhumphries2323** [comment]
Ok, I will add this to the list for the next update (hopefully tomorrow or Monday with the imagesplitter program which will also help). Appreciate it!
